# This is a basic workflow to help you get started with Actions

name: Deploy to Wiki Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run deployment webhook
        env:
          SUPER_SECRET: ${{ secrets.DEPLOY_KEY }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
        run: |
          echo "Running webhook, see result below..."
          echo "Repo: $REPO"
          wget --content-on-error -q -O - "https://scratch-wiki.info/service_api/deploy.php?repo=$REPO&branch=$BRANCH&secret=$SUPER_SECRET"
